version: '2.1'

services:
  product:
    image: product-service:0.0.5
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    image: recommendation-service:0.0.5
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    image: review-service:0.0.5
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    image: product-composite-service:0.0.5
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak.ucb.edu.bo:8080/realms/DemoUCB
    extra_hosts:
      - "keycloak.ucb.edu.bo:host-gateway"
    depends_on:
      rabbitmq:
        condition: service_healthy

  mongodb:
    image: mongo:8
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
#      test: "mongostat -n 1"
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  postgresql:
    image: postgres:16-alpine
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=review-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d review-db'"]
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    image: rabbitmq:3.11.8-management
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    image: eureka-server:latest
    mem_limit: 512m

  gateway:
    image: gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SSL_KEY_STORE=file:/keystore/edge-test.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak.ucb.edu.bo:8080/realms/DemoUCB
    extra_hosts:
      - "keycloak.ucb.edu.bo:host-gateway"
    volumes:
      - $PWD/keystore:/keystore
    mem_limit: 512m
    ports:
      - "8443:8443"