server:
  port: 8080

spring:
  application:
    name: gateway-service  
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        - id: usuarios-v1-direct
          uri: lb://usuarios-service
          predicates:
            - Path=/v1/usuario,/v1/usuario/**
          order: 1
        
        - id: usuarios-v1-api
          uri: lb://usuarios-service
          predicates:
            - Path=/api/v1/usuario,/api/v1/usuario/**
          filters:
            - RewritePath=/api(?<segment>.*), $\{segment}
          order: 1
        
        - id: usuarios-openapi-swagger-ui
          uri: lb://usuarios-service
          predicates:
            - Path=/openapi/swagger-ui.html,/openapi/swagger-ui/**
          order: 1
        
        - id: usuarios-openapi-docs
          uri: lb://usuarios-service
          predicates:
            - Path=/openapi/v3/api-docs,/openapi/v3/api-docs/**
          order: 1
        
        # ============ SWAGGER/OPENAPI (Alias sin /openapi/) ============
        - id: usuarios-swagger-ui-alias
          uri: lb://usuarios-service
          predicates:
            - Path=/swagger-ui.html,/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui(?<segment>.*), /openapi/swagger-ui$\{segment}
          order: 1
        
        - id: usuarios-api-docs-alias
          uri: lb://usuarios-service
          predicates:
            - Path=/v3/api-docs,/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs(?<segment>.*), /openapi/v3/api-docs$\{segment}
          order: 1
        
        - id: usuarios-webjars
          uri: lb://usuarios-service
          predicates:
            - Path=/webjars/**
          order: 1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:4200"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: gateway-service
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.web: DEBUG
    reactor.netty: INFO